import { StyleSheet } from "react-native";
import { color } from "../../../../utils";
export const styles = StyleSheet.create({
  containerProfileCover: {
    width: "100%",
    height: 150,
    padding: 0,
    backgroundColor: color.light.corporate,
    justifyContent: "center",
    alignContent: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#ffff",
  },
  containerProfileCoverChecked: {
    width: "100%",
    height: 150,
    padding: 2,
    backgroundColor: "4BB543",
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#ffff",
  },
  addProfileCoverIcon: {
    transform: [{ rotateY: "180deg" }],
  },
  addProfileAvatarIcon: {
    transform: [{ rotateY: "180deg" }],
  },
  containerProfileAvatar: {
    marginHorizontal: 15,
    marginTop: -40,
    width: 80,
    height: 80,
    borderWidth: 2,
    borderRadius: 50,
    borderColor: "#ffff",
    backgroundColor: color.light.textSecondary,
    justifyContent: "center",
    alignItems: "center",
  },
  containerProfileAvatarChecked: {
    marginHorizontal: 15,
    marginTop: -40,
    width: 80,
    height: 80,
    borderWidth: 2,
    borderRadius: 50,
    borderColor: "#ffff",
    backgroundColor: "#4BB543",
    opacity: 0.9,
    justifyContent: "center",
    alignItems: "center",
  },
});
